### ISSUE TITLE
Feasibility Study

### ISSUE THREAD

**Issue by sshaheen** [connoremma/SoftwareEngineeringProject#1]
Haiii Guiyyez we should finish the Feasibility Study Report
:~)

**Comment by connoremma** [comment]
okayyyyeeeee ~(^.^~)

**Comment by xlzhen** [comment]
@connoremma I hope everything happened to me will happen to you someday in your life. So that you will know how disgusting and vulgar you all were. I realize everything started from you and you might expect it to go it this way. Your friends that I reported are ridiculous as well. I believe in karma. I know you all will pay back for what you did.  Especially you. Always seeking attentions and wanting to be "the topic" and "drag" me into your stupid game.

**Comment by xlzhen** [comment]
@connoremma  It seems like you are really afraid others know what happened. Is this the reason why you deleted your Instagram right after I posted on it? You are so fake and disgusting. You, your good friends and your ex-girlfriend had created so many craps for me, now you are hiding away as if nothing had happened. So ridiculous. Selfish, self-centered and lack of morality.
